version: 2.1
jobs:
  build:
    docker: 
      - image: yuucu/aglio
    steps:
      - checkout
      - run:
          name: convert to html
          command: aglio -i ./src/main.md -o ./output/main.html
          # deploy:
